[package]
name = "openai_dive"
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/tjardoo/openai-client"
description = "OpenAI Dive is a Rust API client that allows you to interact with the OpenAI API."

[dependencies]
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
