[package]
name = "openai_dive"
version = "0.1.4"
edition = "2021"
license = "MIT"
description = "OpenAI Dive is an async Rust API client that allows you to interact with the OpenAI API."
repository = "https://github.com/tjardoo/openai-client"
documentation = "https://docs.rs/openai_dive"

[dependencies]
reqwest = { version = "0.11", features = ["json", "stream", "multipart"] }
reqwest-eventsource = "0.4.0"
futures = "0.3"
tokio = { version = "1", features = [] }
tokio-util = { version = "0.7", features = ["codec"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
