[package]
name = "openai_dive"
version = "0.1.3"
edition = "2021"
license = "MIT"
repository = "https://github.com/tjardoo/openai-client"
description = "OpenAI Dive is an async Rust API client that allows you to interact with the OpenAI API."

[dependencies]
reqwest = { version = "0.11", features = ["json", "stream", "multipart"] }
tokio = { version = "1", features = [] }
tokio-util = { version = "0.7", features = ["codec"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
