[package]
name = "openai_dive"
version = "0.2.1"
edition = "2021"
license = "MIT"
description = "OpenAI Dive is an async Rust API client that allows you to interact with the OpenAI API."
repository = "https://github.com/tjardoo/openai-client"
documentation = "https://docs.rs/openai_dive"
keywords = ["openai", "async"]

[dependencies]
reqwest = { version = "0.11", features = ["json", "stream", "multipart"] }
reqwest-eventsource = { version = "0.4.0", optional = true }
futures = { version = "0.3", optional = true }
tokio = { version = "1", features = [] }
tokio-util = { version = "0.7", features = ["codec"] }
tokio-stream = { version = "0.1", optional = true }
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"

[features]
default = []
stream = ["dep:reqwest-eventsource", "dep:futures", "dep:tokio-stream"]
