[workspace]
members = [
    "list_models",
    "retrieve_model",
    "create_chat_completion",
    "create_chat_completion_stream",
    "create_chat_completion_default",
    "create_edit",
    "create_edit_default",
    "create_image",
    "create_image_edit",
    "create_image_variation",
    "create_embedding",
    "create_transcription",
    "create_translation",
    "list_files",
    "upload_file",
    "delete_file",
    "retrieve_file",
    "retrieve_file_content",
    "create_fine_tune",
    "list_fine_tunes",
    "retrieve_fine_tune",
    "cancel_fine_tune",
    "list_fine_tune_events",
    "delete_fine_tune_model",
    "create_moderation",
]
