[workspace]
members = [
    "list_models",
    "retrieve_model",
    "create_completion",
    "create_completion_stream",
    "create_chat_completion",
    "create_chat_completion_stream",
    "create_edit",
    "create_image",
    "create_image_edit",
    "create_image_variation",
    "create_embedding",
    "create_moderation",
]
