[workspace]
resolver = "2"
members = [
    "create_chat_completion",
    "create_chat_completion_stream",
    "create_image_chat_completion",
    "function_calling",
    "function_calling_stream",
    "rate_limit_headers",
]
